MainProjectMVC/Models/ErrorViewModel.cs
using System;

namespace MainProjectMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MainProjectMVC/Controllers/HomeController.cs
using MainProjectMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MainProjectMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MainProjectMVC/Controllers/StudValuesController.cs
using EntityFramework;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MainProjectMVC.Controllers
{
    public class StudValuesController : Controller
    {
        private readonly IStudentsRepository _Result;
        private readonly string _connectionstring;
        public StudValuesController(IStudentsRepository res, IConfiguration configuration)
        {
            _Result = res;
            _connectionstring = configuration.GetConnectionString("DbConnection");
        }

        // GET: StudValuesController
        public ActionResult Index()
        {
            var Results = _Result.GetAllDetails();
            return View("List",Results);
        }

        // GET: StudValuesController/Details/5
        public ActionResult Details(long id)
        {
            var pro = _Result.GetbyID(id);
            return View("Details", pro);
        }

        // GET: StudValuesController/Create
        //both create and edit in single view control for GET method
        public ActionResult Create(long ? id)
        {
            if (id.HasValue)
            {
                var final = _Result.GetbyID(id.Value);
              
                return View("Create", final);
            }
            else
            {
                var final = new StudentDetails();
                return View ("Create", final);
            }
        }

        // POST: StudValuesController/Create
        [HttpPost]
        //  [ValidateAntiForgeryToken]
        //both create and edit in single view control for POST method
        public ActionResult Creates(StudentDetails final)
        {
            try
            {
                if(final.StudentID==0)
                {
                    _Result.Insert(final);

                }
                else
                {
                    _Result.Update(final.StudentID, final);
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        // GET: StudValuesController/Delete/5
        public ActionResult Delete(int id)
        {
            var pro = _Result.GetbyID(id);
            return View("Delete", pro);
        }

        // POST: StudValuesController/Delete/5
        [HttpPost]
       // [ValidateAntiForgeryToken
        public ActionResult Deletes(int StudentID)
        {

            try
            {
                _Result.Delete(StudentID);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        [HttpGet]
        [Route("~/api/subjects")]
        public ActionResult Sub()
        {
            try
            {
                var sub = Allsubject();
                return Ok(sub.ToList());
            }
            catch(Exception )
            {
                return View();
            }
        }

        private List<SubjectsModel>Allsubject()
        {
            List<SubjectsModel> subjects = new List<SubjectsModel>();
            SubjectsModel detail = new SubjectsModel();
            detail.ID = 1;
            detail.Subjectname = "CSE";
            subjects.Add(detail);
            SubjectsModel result = new SubjectsModel();
            result.ID = 2;
            result.Subjectname = "Physics";
            subjects.Add(result);
            SubjectsModel final = new SubjectsModel();
            final.ID = 3;
            final.Subjectname = "Commerce";
            subjects.Add(final);
            return subjects;
        }
        //email validation controller

        /*[HttpPost]
        public ActionResult CheckEmailExists(string email)
        {
            bool emailExists;
            using (var dbcontxt = new Dbcontxt())
            {
                
            }

                /// Perform database query to check if the email already exists


                // Return JSON response indicating whether the email exists
                return Json(new { exists = emailExists });
        }*/
    }
}

MainProjectMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4" style="font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif">Welcome to TECHSchool.Com</h1>
    <p>Learn about the New Technologies <a href="https://www.techneurons.com/#s1">with TECH School</a>.</p>
    <img class="img-fluid" src="/Images/techimg.jpg" alt="TECHSchool" width="1000" height="1000">
</div>

MainProjectMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MainProjectMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
  
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <nav class="navbar navbar-light bg-light">
                    <div class="container">
                        <a class="navbar-brand" href="#">
                            <img src="/images/tickets.jpg" alt="tickets" width="30" height="24"><b> AD TECH</b>
                        </a>
                    </div>
                </nav>
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar nav-link text-dark">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @*<li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="StudValues" asp-action="Index">StudentsDetails</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="text-center bg-body-tertiary">
        <div class="container pt-3">
            <section>
                <!-- Google -->
                <a data-mdb-ripple-init
                   class="btn btn-link btn-floating btn-lg text-body m-1"
                   target="_blank" href="https://www.techneurons.com/#s1"
                   role="button"
                   data-mdb-ripple-color="dark">
                    <img src="/Images/google-logo.png" alt="google" width="30" height="24">
                </a>
                <!-- Instagram -->
                <a data-mdb-ripple-init
                   class="btn btn-link btn-floating btn-lg text-body m-1"
                   target="_blank" href="https://www.instagram.com/techneurons/?hl=en"
                   role="button"
                   data-mdb-ripple-color="dark">
                    <img src="/images/instagram-logo.png" alt="instagran" width="30" height="24">
                </a>
                <!-- Linkedin -->
                <a data-mdb-ripple-init
                   class="btn btn-link btn-floating btn-lg text-body m-1"
                   target="_blank" href="https://in.linkedin.com/company/techneuron"
                   role="button"
                   data-mdb-ripple-color="dark">
                    <img src="/images/linkedin-logo.png" alt="linkedin" width="30" height="24">
                </a>
            </section>
        </div>
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05); font-size:smaller">
            <marquee direction="right">&copy;2024 ADTECH[India] All rights reserved</marquee>

        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    
   
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MainProjectMVC/Views/StudValues/Create.cshtml
@model EntityFramework.StudentDetails

@{
    ViewData["Title"] = "Create";
}
@{ 
    var method = "Create";
    if (Model.StudentID > 0)
    {
        method = "Update";
    }
}

<h1>@method</h1>

<h4>StudentDetails</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name"  class="control-label"></label>
                <input asp-for="Name"  class="form-control" placeholder="enter username" />
                <input asp-for="StudentID" id="StudentID" type="hidden" class="form-control" />
                <span asp-validation-for="Name" id="chkname"  class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DOB" class="control-label"></label>
                <input asp-for="DOB" type="text"  class="form-control"  />
                
                <span asp-validation-for="DOB" id="chkdob" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" placeholder="enter age" />
                
                <span asp-validation-for="Age" id="chkage" class="text-danger"></span>
            </div>
            <div class="radio-btn label">
                <label>Gender</label><br />

                <input asp-for="Gender" type="radio" name="radio" id="male" value="male">
                <label asp-for="Gender" for="radio">Male</label>
                <input asp-for="Gender" type="radio" name="radio" id="female" value="female">
                <label asp-for="Gender" for="radio">Female</label>

            </div>
            <div>
                <span asp-validation-for="Gender" id="errgender" class="text-danger"></span>
            </div>

            @*<div class="form-group">
            <label asp-for="Gender" class="control-label"></label>
            <input asp-for="Gender" class="form-control" />
            <span asp-validation-for="Gender" class="text-danger"></span>
        </div>*@
            <div class="form-group">
                <label asp-for="MobileNum" class="control-label"></label>
                <input asp-for="MobileNum" class="form-control" placeholder="enter phnnumber"  />
                <span asp-validation-for="MobileNum" id="chknum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Emailid" class="control-label"></label>
                <input asp-for="Emailid"  class="form-control" placeholder="enter emailid"/>
                <span asp-validation-for="Emailid" id="chkemail" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-12">
                    Male
                    @Html.DropDownListFor(model => model.Subject, "")
                    Female
                    @Html.DropDownListFor(model => model.Subject, "Female")
                </div>
            </div>*@

            <div class="form-group">
                <label asp-for="Subject" class="control-label"></label>
                <select  id="drpsubject"  asp-for="Subject" class="form-control" ></select>
                <input id="hdnsub" type="hidden" asp-for="Subject" />
                <span asp-validation-for="Subject" id="drpsub"  class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="button"   id="create" value="@method" class="btn btn-outline-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script>

        $(document).ready(function () {
           
            $('#DOB').daterangepicker({
                singleDatePicker: true,
                showDropdowns: true,
                autoApply: true,
                autoUpdateInput: true,
                minYear: 1980,
                maxYear: parseInt(moment().format('YYYY'), 10) + 2
            }, function (start, end, label) {
                var years = moment().diff(start, 'years');
                //    alert("You are " + years + " years old!");
            });


            ////Date range picker with time picker
            $('#DOB').on('apply.daterangepicker', function (ev, picker) {

                $('#hdnDOB').val($('#DOB').val());
            });
            $("#DOB").on('change keyup paste mouseup', function () {
                $('#hdnDateofBirth').val($('#DateofBirth').val());
            });

        
        
        //code to do the validation and send the data to server
        $("#create").click(function () {
            if (validation()) {
                @*$(document).ready(function () {
                    $("#create").click(function () {
                        // Get values from form fields
                        var email = document.getElementById("Emailid").value;
                        var num = $("#phone").val();

                        // Perform client-side validation
                        if (emailExists(email) || phoneExists(phone)) {
                            // Display error message
                            $("#errorMessage").text("Email or phone number already exists. Please provide a unique email and phone number.");
                            // Prevent form submission
                            return false;
                        }
                    });*@
                var name = document.getElementById("Name").value;
                var dob = document.getElementById("DOB").value;
                var age = document.getElementById("Age").value;
                var studentid = document.getElementById("StudentID").value;
                var num = document.getElementById("MobileNum").value;
                var email = document.getElementById("Emailid").value;
                var spansub = document.getElementById("drpsubject");
                var sub = spansub.options[spansub.selectedIndex].value;
                var radios = document.getElementsByName("radio");
                var radgender = "";
                for (var i = 0, length = radios.length; i < length; i++) {
                    if (radios[i].checked) {
                        radgender = radios[i].value;
                        break;
                    }
                }

                var resultdata = {
                    "StudentID": studentid,
                    "Name": name,
                    "DOB": dob,
                    "Age": age,
                    "Gender": radgender,
                    "MobileNum": num,
                    "Emailid": email,
                    "Subject": sub,
                };



                debugger;
                $.ajax({
                    type: "POST",
                    url: "/StudValues/Creates",
                    data: resultdata,
                    success: function (data) {
                        alert("success");
                        window.location.href = "/studvalues/index";
                    },
                });
            }

        });


        //getting the subject data from server and binding it in the Dropdown
        $.ajax({
            type: "GET",
            url: "/api/subjects",
            data: "{}",
            success: function (data) {
                debugger;
                var string = '<option value="-1">--- Please Select ---</option>';
                for (var i = 0; i < data.length; i++) {
                    string += '<option value="' + data[i].id + '">' + data[i].subjectname + '</option>';
                }
                $("#drpsubject").html(string);

                $("#drpsubject").val($("#hdnsub").val());
            }
        });
        
    });


    debugger;
    function validation()
    {
        var name = document.getElementById("Name").value;
        var spanname = document.getElementById("chkname");

        var age = document.getElementById("Age").value;
        var spanage = document.getElementById("chkage");


        var num = document.getElementById("MobileNum").value;
        var spannum = document.getElementById("chknum");

        var email = document.getElementById("Emailid").value;
        var mailformat = new RegExp( /^[^\s@@]+@@[^\s@@]+\.[^\s@@]+$/);
        var spanemail = document.getElementById("chkemail");

        var dob = document.getElementById("DOB").value;
        var spandob = document.getElementById("chkdob");





        var isvalid = true;
        debugger;
        //name validation
        if (name == "" || name.length == 0)
        {
            spanname.innerText = "please enter your name";
            spanname.style.display = "block";
            isvalid = false;
        }
        else
        {
            spanname.style.display = "none";
        }

        debugger;
       //age validation
        if (age === "" || age < 18) {
            spanage.innerText = "please enter your age";
            spanage.style.display = "block";
            isvalid = false;
        }
        else
        {
            spanage.style.display = "none";
        }
        debugger;
        //mobile validation
        if (num === "" || num.length != 10) {
            spannum.innerText = "please enter your num(must be 10 digit)";
            spannum.style.display = "block";
            isvalid = false;
        }
        else {
            spannum.style.display = "none";
        }
        debugger;
        //email validation

        if (email == "" || !(mailformat.test(email))) {
            spanemail.innerText = "please enter your emailid";
            spanemail.style.display = "block";
            isvalid = false;
        }
        else {
            spanemail.style.display = "none";
        }
        debugger;
        //dob validation
        if (dob == "" || dob == "0001-01-01T00:00") {
            spandob.innerText = "please enter your dob";
            spandob.style.display = "block";
            isvalid = false;
        }
        else {
            spandob.style.display = "none";
        }
        debugger;
        //radio validation
        var radios = document.getElementsByName("radio");
        var value = ""
        for (var i = 0, length = radios.length; i < length; i++) {
            if (radios[i].checked) {
                value = radios[i].value;
                break;
            }
        }

        var gender = document.getElementById("errgender");
        if (!value) {
            gender.innerText = "Please Select Your Gender";
            gender.style.display = "block";
        }
        else {
            gender.style.display = "none";
        }


        //subject validation
        var spansub = document.getElementById("drpsubject");
        var sub = spansub.options[spansub.selectedIndex].value;
        var spansubject = document.getElementById("drpsub");
        if (sub == "" || sub == -1 || sub == 0) {
            spansub.style.borderColor = "red";
            spansubject.innerText = "please select subject";
            spansubject.style.display = "block";
            isvalid = false;
        }
        else {
            spansub.style.borderColor = "black";
            spansubject.style.display = "none";
        }
        return isvalid;
    }




    </script>
}

MainProjectMVC/Views/StudValues/Delete.cshtml
@model EntityFramework.StudentDetails

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>StudentDetails</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DOB)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DOB)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MobileNum)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MobileNum)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Emailid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Emailid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subject)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subject)
        </dd>
    </dl>
    
    <form asp-action="Deleteid">
        <input type="hidden" asp-for="StudentID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MainProjectMVC/Views/StudValues/Details.cshtml
@model EntityFramework.StudentDetails

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>StudentDetails</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DOB)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DOB)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MobileNum)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MobileNum)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Emailid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Emailid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subject)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subject)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.StudentID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MainProjectMVC/Views/StudValues/List.cshtml
@model IEnumerable<EntityFramework.StudentDetails>

@{
    ViewData["Title"] = "List";
}
@section Scripts{ 
<script>


    $(document).ready(function () {
        $(".del").click(function () {
            debugger;
            var id = $(this).attr("dataid");
            if (confirm("Are you sure want to delete")) {
                var post = {
                    "StudentID": id
                };
                $.ajax({
                    type: "Post",
                    url: "/StudValues/Deletes",
                    data: post,
                    success: function () {
                        alert("Deleted");
                    }


                });
            }

            
        });

    });
</script>
}
<h1>List</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DOB)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MobileNum)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Emailid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Subject)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DOB)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MobileNum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Emailid)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Subject)
            </td>
            <td>
                <a asp-action="Create" asp-route-id="@item.StudentID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.StudentID">Details</a> |
                <a href="" class="del" dataid="@item.StudentID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>